name: Build and Test
on:
  pull_request:
  push:
    branches-ignore:
      - publish
      - mdbook
jobs:

  build-and-test:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        py: [311]
        allow-fail: [false]
        include:
          - os: macos-12
            py: 311
            allow-fail: true

    steps:
      - uses: actions/checkout@v3.5.3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: nain4 # The name of the Cachix cache
          # If you chose signing key for write access
          #signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_JACG_NAIN4 }}'

      - name: Nix build
        run: nix develop

      - name: Test nain4
        run: nix develop -c just

      - name: nix-shell
        run: nix-shell --run just

      - name: Run G4 examples
        run: nix develop -c just g4-examples/run-examples-that-work
